name: quality
# on:
#   push:
#     branches: ["master"]
#   pull_request:
#     branches: ["master"]
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16

#       - name: Install dependencies
#         run: npm ci --legacy-peer-deps

#       # - name: Install Playwright
#       #   run: npx playwright install --with-deps

#       # - name: Build Storybook
#       #   run: npm run build-storybook --quiet

#       - name: Serve Storybook and run tests
#         run: npm run test-storybook:ci
